// Auto-generated from TelegramGiftsAssests-main (Gifts_Details.json + webp/by_name).
// Реальные цены: floor_price_ton (TON). Пути — к реальным webp. НЕ править руками.
export const giftsData = [
  { id: 'artisan_brick', name: "Artisan Brick", price: 54.62, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/artisan_brick.webp' },
  { id: 'astral_shard', name: "Astral Shard", price: 120, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/astral_shard.webp' },
  { id: 'bday_candle', name: "B-Day Candle", price: 4.4, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/bday_candle.webp' },
  { id: 'berry_box', name: "Berry Box", price: 7.2, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/berry_box.webp' },
  { id: 'big_year', name: "Big Year", price: 3.15, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/big_year.webp' },
  { id: 'bling_binky', name: "Bling Binky", price: 22.68, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/bling_binky.webp' },
  { id: 'bonded_ring', name: "Bonded Ring", price: 36.88, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/bonded_ring.webp' },
  { id: 'bow_tie', name: "Bow Tie", price: 4.35, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/bow_tie.webp' },
  { id: 'bunny_muffin', name: "Bunny Muffin", price: 6.9, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/bunny_muffin.webp' },
  { id: 'candy_cane', name: "Candy Cane", price: 3.1, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/candy_cane.webp' },
  { id: 'chill_flame', name: "Chill Flame", price: 2.95, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/chill_flame.webp' },
  { id: 'clover_pin', name: "Clover Pin", price: 4.09, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/clover_pin.webp' },
  { id: 'cookie_heart', name: "Cookie Heart", price: 4.3, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/cookie_heart.webp' },
  { id: 'crystal_ball', name: "Crystal Ball", price: 10.9, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/crystal_ball.webp' },
  { id: 'cupid_charm', name: "Cupid Charm", price: 19.99, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/cupid_charm.webp' },
  { id: 'desk_calendar', name: "Desk Calendar", price: 4.28, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/desk_calendar.webp' },
  { id: 'diamond_ring', name: "Diamond Ring", price: 27.42, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/diamond_ring.webp' },
  { id: 'durovs_cap', name: "Durov’s Cap", price: 420, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/durovs_cap.webp' },
  { id: 'durovs_glasses', name: "Durov’s Glasses", price: 133.34, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/durovs_glasses.webp' },
  { id: 'easter_egg', name: "Easter Egg", price: 3.21, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/easter_egg.webp' },
  { id: 'electric_skull', name: "Electric Skull", price: 22.81, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/electric_skull.webp' },
  { id: 'eternal_candle', name: "Eternal Candle", price: 4.94, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/eternal_candle.webp' },
  { id: 'eternal_rose', name: "Eternal Rose", price: 23.91, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/eternal_rose.webp' },
  { id: 'evil_eye', name: "Evil Eye", price: 6.58, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/evil_eye.webp' },
  { id: 'faith_amulet', name: "Faith Amulet", price: 4.57, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/faith_amulet.webp' },
  { id: 'flying_broom', name: "Flying Broom", price: 9.95, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/flying_broom.webp' },
  { id: 'fresh_socks', name: "Fresh Socks", price: 3.75, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/fresh_socks.webp' },
  { id: 'gem_signet', name: "Gem Signet", price: 57.83, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/gem_signet.webp' },
  { id: 'genie_lamp', name: "Genie Lamp", price: 31.47, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/genie_lamp.webp' },
  { id: 'ginger_cookie', name: "Ginger Cookie", price: 3.5, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/ginger_cookie.webp' },
  { id: 'hanging_star', name: "Hanging Star", price: 7.6, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/hanging_star.webp' },
  { id: 'happy_brownie', name: "Happy Brownie", price: 3.82, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/happy_brownie.webp' },
  { id: 'heart_locket', name: "Heart Locket", price: 1006.74, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/heart_locket.webp' },
  { id: 'heroic_helmet', name: "Heroic Helmet", price: 181.51, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/heroic_helmet.webp' },
  { id: 'hex_pot', name: "Hex Pot", price: 3.74, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/hex_pot.webp' },
  { id: 'holiday_drink', name: "Holiday Drink", price: 3.22, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/holiday_drink.webp' },
  { id: 'homemade_cake', name: "Homemade Cake", price: 4.44, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/homemade_cake.webp' },
  { id: 'hypno_lollipop', name: "Hypno Lollipop", price: 3.4, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/hypno_lollipop.webp' },
  { id: 'ice_cream', name: "Ice Cream", price: 3.2, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/ice_cream.webp' },
  { id: 'input_key', name: "Input Key", price: 4.96, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/input_key.webp' },
  { id: 'instant_ramen', name: "Instant Ramen", price: 3.13, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/instant_ramen.webp' },
  { id: 'ion_gem', name: "Ion Gem", price: 64.01, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/ion_gem.webp' },
  { id: 'ionic_dryer', name: "Ionic Dryer", price: 13.98, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/ionic_dryer.webp' },
  { id: 'jackinthebox', name: "Jack-in-the-Box", price: 3.9, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/jackinthebox.webp' },
  { id: 'jelly_bunny', name: "Jelly Bunny", price: 6.88, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/jelly_bunny.webp' },
  { id: 'jester_hat', name: "Jester Hat", price: 3.3, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/jester_hat.webp' },
  { id: 'jingle_bells', name: "Jingle Bells", price: 6.6, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/jingle_bells.webp' },
  { id: 'jolly_chimp', name: "Jolly Chimp", price: 6.49, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/jolly_chimp.webp' },
  { id: 'joyful_bundle', name: "Joyful Bundle", price: 6.47, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/joyful_bundle.webp' },
  { id: 'khabibs_papakha', name: "Khabib’s Papakha", price: 22, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/khabibs_papakha.webp' },
  { id: 'kissed_frog', name: "Kissed Frog", price: 39.57, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/kissed_frog.webp' },
  { id: 'liberty_figure', name: "Liberty Figure", price: 3.52, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/liberty_figure.webp' },
  { id: 'light_sword', name: "Light Sword", price: 5.5, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/light_sword.webp' },
  { id: 'lol_pop', name: "Lol Pop", price: 3.17, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/lol_pop.webp' },
  { id: 'loot_bag', name: "Loot Bag", price: 113.48, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/loot_bag.webp' },
  { id: 'love_candle', name: "Love Candle", price: 7, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/love_candle.webp' },
  { id: 'love_potion', name: "Love Potion", price: 12.99, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/love_potion.webp' },
  { id: 'low_rider', name: "Low Rider", price: 48.03, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/low_rider.webp' },
  { id: 'lunar_snake', name: "Lunar Snake", price: 2.95, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/lunar_snake.webp' },
  { id: 'lush_bouquet', name: "Lush Bouquet", price: 5.29, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/lush_bouquet.webp' },
  { id: 'mad_pumpkin', name: "Mad Pumpkin", price: 9.5, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/mad_pumpkin.webp' },
  { id: 'magic_potion', name: "Magic Potion", price: 49, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/magic_potion.webp' },
  { id: 'mighty_arm', name: "Mighty Arm", price: 113.62, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/mighty_arm.webp' },
  { id: 'mini_oscar', name: "Mini Oscar", price: 67.84, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/mini_oscar.webp' },
  { id: 'money_pot', name: "Money Pot", price: 4, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/money_pot.webp' },
  { id: 'mood_pack', name: "Mood Pack", price: 3.8, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/mood_pack.webp' },
  { id: 'moon_pendant', name: "Moon Pendant", price: 5.35, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/moon_pendant.webp' },
  { id: 'mousse_cake', name: "Mousse Cake", price: 4.41, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/mousse_cake.webp' },
  { id: 'nail_bracelet', name: "Nail Bracelet", price: 100, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/nail_bracelet.webp' },
  { id: 'neko_helmet', name: "Neko Helmet", price: 33.2, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/neko_helmet.webp' },
  { id: 'party_sparkler', name: "Party Sparkler", price: 3.6, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/party_sparkler.webp' },
  { id: 'perfume_bottle', name: "Perfume Bottle", price: 62.34, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/perfume_bottle.webp' },
  { id: 'pet_snake', name: "Pet Snake", price: 3.3, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/pet_snake.webp' },
  { id: 'plush_pepe', name: "Plush Pepe", price: 5298, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/plush_pepe.webp' },
  { id: 'pool_float', name: "Pool Float", price: 3.06, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/pool_float.webp' },
  { id: 'precious_peach', name: "Precious Peach", price: 269.88, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/precious_peach.webp' },
  { id: 'pretty_posy', name: "Pretty Posy", price: 4.49, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/pretty_posy.webp' },
  { id: 'rare_bird', name: "Rare Bird", price: 22.28, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/rare_bird.webp' },
  { id: 'record_player', name: "Record Player", price: 11.11, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/record_player.webp' },
  { id: 'restless_jar', name: "Restless Jar", price: 4.4, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/restless_jar.webp' },
  { id: 'sakura_flower', name: "Sakura Flower", price: 8, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/sakura_flower.webp' },
  { id: 'santa_hat', name: "Santa Hat", price: 3.5, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/santa_hat.webp' },
  { id: 'scared_cat', name: "Scared Cat", price: 176.1, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/scared_cat.webp' },
  { id: 'sharp_tongue', name: "Sharp Tongue", price: 38.97, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/sharp_tongue.webp' },
  { id: 'signet_ring', name: "Signet Ring", price: 31.48, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/signet_ring.webp' },
  { id: 'skull_flower', name: "Skull Flower", price: 8.99, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/skull_flower.webp' },
  { id: 'sky_stilettos', name: "Sky Stilettos", price: 16.9, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/sky_stilettos.webp' },
  { id: 'sleigh_bell', name: "Sleigh Bell", price: 5.92, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/sleigh_bell.webp' },
  { id: 'snake_box', name: "Snake Box", price: 3.11, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/snake_box.webp' },
  { id: 'snoop_cigar', name: "Snoop Cigar", price: 12.41, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/snoop_cigar.webp' },
  { id: 'snoop_dogg', name: "Snoop Dogg", price: 4.62, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/snoop_dogg.webp' },
  { id: 'snow_globe', name: "Snow Globe", price: 4.03, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/snow_globe.webp' },
  { id: 'snow_mittens', name: "Snow Mittens", price: 4.09, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/snow_mittens.webp' },
  { id: 'spiced_wine', name: "Spiced Wine", price: 4.2, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/spiced_wine.webp' },
  { id: 'spring_basket', name: "Spring Basket", price: 4.9, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/spring_basket.webp' },
  { id: 'spy_agaric', name: "Spy Agaric", price: 4.18, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/spy_agaric.webp' },
  { id: 'star_notepad', name: "Star Notepad", price: 3.76, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/star_notepad.webp' },
  { id: 'stellar_rocket', name: "Stellar Rocket", price: 4.2, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/stellar_rocket.webp' },
  { id: 'surge_board', name: "Surge Board", price: 6.31, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/surge_board.webp' },
  { id: 'swag_bag', name: "Swag Bag", price: 4.98, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/swag_bag.webp' },
  { id: 'swiss_watch', name: "Swiss Watch", price: 43, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/swiss_watch.webp' },
  { id: 'tama_gadget', name: "Tama Gadget", price: 3.15, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/tama_gadget.webp' },
  { id: 'timeless_book', name: "Timeless Book", price: 3.6, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/timeless_book.webp' },
  { id: 'top_hat', name: "Top Hat", price: 9.25, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/top_hat.webp' },
  { id: 'toy_bear', name: "Toy Bear", price: 34.99, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/toy_bear.webp' },
  { id: 'trapped_heart', name: "Trapped Heart", price: 12.87, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/trapped_heart.webp' },
  { id: 'ufc_strike', name: "UFC Strike", price: 13.26, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/ufc_strike.webp' },
  { id: 'valentine_box', name: "Valentine Box", price: 9.66, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/valentine_box.webp' },
  { id: 'vice_cream', name: "Vice Cream", price: 3.12, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/vice_cream.webp' },
  { id: 'victory_medal', name: "Victory Medal", price: 3.88, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/victory_medal.webp' },
  { id: 'vintage_cigar', name: "Vintage Cigar", price: 35.33, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/vintage_cigar.webp' },
  { id: 'voodoo_doll', name: "Voodoo Doll", price: 33.89, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/voodoo_doll.webp' },
  { id: 'westside_sign', name: "Westside Sign", price: 85, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/westside_sign.webp' },
  { id: 'whip_cupcake', name: "Whip Cupcake", price: 3.3, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/whip_cupcake.webp' },
  { id: 'winter_wreath', name: "Winter Wreath", price: 3.21, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/winter_wreath.webp' },
  { id: 'witch_hat', name: "Witch Hat", price: 4.38, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/witch_hat.webp' },
  { id: 'xmas_stocking', name: "Xmas Stocking", price: 3.09, currency: 'TON', image: 'TelegramGiftsAssests-main/webp/by_name/xmas_stocking.webp' },
];

export const giftsCount = 117;


export const standardGifts = [
  { id: 'heart', name: 'Heart', priceStars: 15, image: 'standard-gifts/heart.png' },
  { id: 'teddy-bear', name: 'Teddy Bear', priceStars: 15, image: 'standard-gifts/teddy-bear.png' },
  { id: 'gift-box', name: 'Gift Box', priceStars: 25, image: 'standard-gifts/gift-box.png' },
  { id: 'red-rose', name: 'Red Rose', priceStars: 25, image: 'standard-gifts/red-rose.png' },
  { id: 'birthday-cake', name: 'Birthday Cake', priceStars: 50, image: 'standard-gifts/birthday-cake.png' },
  { id: 'bouquet', name: 'Bouquet', priceStars: 50, image: 'standard-gifts/bouquet.png' },
  { id: 'rocket', name: 'Rocket', priceStars: 50, image: 'standard-gifts/rocket.png' },
  { id: 'trophy', name: 'Trophy', priceStars: 100, image: 'standard-gifts/trophy.png' },
  { id: 'diamond-ring', name: 'Diamond Ring', priceStars: 100, image: 'standard-gifts/diamond-ring.png' },
  { id: 'diamond', name: 'Diamond', priceStars: 100, image: 'standard-gifts/diamond.png' },
  { id: 'champagne', name: 'Champagne', priceStars: 50, image: 'standard-gifts/champagne.png' }
];

