// Auto-generated gifts config - one object per FILE (PNG, no background).
// Each variant inherits the name/price of its collection by prefix.
export const giftsData = [
  { id: 'artisan_bricks__art1-Photoroom', name: 'Artisan Bricks', price: 61.9, currency: 'TON', image: 'gift image/art1-Photoroom.png' },
  { id: 'artisan_bricks__art2-Photoroom', name: 'Artisan Bricks', price: 61.9, currency: 'TON', image: 'gift image/art2-Photoroom.png' },
  { id: 'artisan_bricks__art-Photoroom', name: 'Artisan Bricks', price: 61.9, currency: 'TON', image: 'gift image/art-Photoroom.png' },
  { id: 'astral_shards__ast1-Photoroom', name: 'Astral Shards', price: 130, currency: 'TON', image: 'gift image/ast1-Photoroom.png' },
  { id: 'astral_shards__ast2-Photoroom', name: 'Astral Shards', price: 130, currency: 'TON', image: 'gift image/ast2-Photoroom.png' },
  { id: 'astral_shards__ast3-Photoroom', name: 'Astral Shards', price: 130, currency: 'TON', image: 'gift image/ast3-Photoroom.png' },
  { id: 'astral_shards__ast-Photoroom', name: 'Astral Shards', price: 130, currency: 'TON', image: 'gift image/ast-Photoroom.png' },
  { id: 'b_day_candles__bda1-Photoroom', name: 'B-Day Candles', price: 4.17, currency: 'TON', image: 'gift image/bda1-Photoroom.png' },
  { id: 'b_day_candles__bda2-Photoroom', name: 'B-Day Candles', price: 4.17, currency: 'TON', image: 'gift image/bda2-Photoroom.png' },
  { id: 'b_day_candles__bda-Photoroom', name: 'B-Day Candles', price: 4.17, currency: 'TON', image: 'gift image/bda-Photoroom.png' },
  { id: 'berry_boxes__ber', name: 'Berry Boxes', price: 8.34, currency: 'TON', image: 'gift image/ber.png' },
  { id: 'berry_boxes__ber1-Photoroom', name: 'Berry Boxes', price: 8.34, currency: 'TON', image: 'gift image/ber1-Photoroom.png' },
  { id: 'big_years__big1-Photoroom', name: 'Big Years', price: 3.41, currency: 'TON', image: 'gift image/big1-Photoroom.png' },
  { id: 'big_years__big-Photoroom', name: 'Big Years', price: 3.41, currency: 'TON', image: 'gift image/big-Photoroom.png' },
  { id: 'bonded_rings__bon1-Photoroom', name: 'Bonded Rings', price: 38, currency: 'TON', image: 'gift image/bon1-Photoroom.png' },
  { id: 'bonded_rings__bon-Photoroom', name: 'Bonded Rings', price: 38, currency: 'TON', image: 'gift image/bon-Photoroom.png' },
  { id: 'candy_canes__can1-Photoroom', name: 'Candy Canes', price: 3.97, currency: 'TON', image: 'gift image/can1-Photoroom.png' },
  { id: 'candy_canes__can-Photoroom', name: 'Candy Canes', price: 3.97, currency: 'TON', image: 'gift image/can-Photoroom.png' },
  { id: 'chill_flames__chi1-Photoroom', name: 'Chill Flames', price: 3.21, currency: 'TON', image: 'gift image/chi1-Photoroom.png' },
  { id: 'chill_flames__chi-Photoroom', name: 'Chill Flames', price: 3.21, currency: 'TON', image: 'gift image/chi-Photoroom.png' },
  { id: 'cookie_hearts__coo1-Photoroom', name: 'Cookie Hearts', price: 4.58, currency: 'TON', image: 'gift image/coo1-Photoroom.png' },
  { id: 'cookie_hearts__coo-Photoroom', name: 'Cookie Hearts', price: 4.58, currency: 'TON', image: 'gift image/coo-Photoroom.png' },
  { id: 'crystal_balls__cry1-Photoroom', name: 'Crystal Balls', price: 12, currency: 'TON', image: 'gift image/cry1-Photoroom.png' },
  { id: 'crystal_balls__cry2-Photoroom', name: 'Crystal Balls', price: 12, currency: 'TON', image: 'gift image/cry2-Photoroom.png' },
  { id: 'crystal_balls__cry-Photoroom', name: 'Crystal Balls', price: 12, currency: 'TON', image: 'gift image/cry-Photoroom.png' },
  { id: 'cupid_charms__cup1-Photoroom', name: 'Cupid Charms', price: 21, currency: 'TON', image: 'gift image/cup1-Photoroom.png' },
  { id: 'cupid_charms__cup2-Photoroom', name: 'Cupid Charms', price: 21, currency: 'TON', image: 'gift image/cup2-Photoroom.png' },
  { id: 'cupid_charms__cup-Photoroom', name: 'Cupid Charms', price: 21, currency: 'TON', image: 'gift image/cup-Photoroom.png' },
  { id: 'diamond_rings__dia1-Photoroom', name: 'Diamond Rings', price: 29.7, currency: 'TON', image: 'gift image/dia1-Photoroom.png' },
  { id: 'diamond_rings__dia-Photoroom', name: 'Diamond Rings', price: 29.7, currency: 'TON', image: 'gift image/dia-Photoroom.png' },
  { id: 'snoop_doggs__dog-Photoroom', name: 'Snoop Doggs', price: 4.20, currency: 'TON', image: 'gift image/dog-Photoroom.png' },
  { id: 'durov_s_caps__dur1-Photoroom', name: 'Durov\'s Caps', price: 390, currency: 'TON', image: 'gift image/dur1-Photoroom.png' },
  { id: 'durov_s_caps__dur-Photoroom', name: 'Durov\'s Caps', price: 390, currency: 'TON', image: 'gift image/dur-Photoroom.png' },
  { id: 'easter_eggs__eas-Photoroom', name: 'Easter Eggs', price: 3.67, currency: 'TON', image: 'gift image/eas-Photoroom.png' },
  { id: 'electric_skulls__ele-Photoroom', name: 'Electric Skulls', price: 23, currency: 'TON', image: 'gift image/ele-Photoroom.png' },
  { id: 'eternal_candles__ete-Photoroom', name: 'Eternal Candles', price: 5.7, currency: 'TON', image: 'gift image/ete-Photoroom.png' },
  { id: 'evil_eyes__evi1-Photoroom', name: 'Evil Eyes', price: 6.70, currency: 'TON', image: 'gift image/evi1-Photoroom.png' },
  { id: 'evil_eyes__evi-Photoroom', name: 'Evil Eyes', price: 6.70, currency: 'TON', image: 'gift image/evi-Photoroom.png' },
  { id: 'flying_brooms__fly-Photoroom', name: 'Flying Brooms', price: 11, currency: 'TON', image: 'gift image/fly-Photoroom.png' },
  { id: 'gem_signets__gem1-Photoroom', name: 'Gem Signets', price: 62.79, currency: 'TON', image: 'gift image/gem1-Photoroom.png' },
  { id: 'gem_signets__gem-Photoroom', name: 'Gem Signets', price: 62.79, currency: 'TON', image: 'gift image/gem-Photoroom.png' },
  { id: 'genie_lamps__gen-Photoroom', name: 'Genie Lamps', price: 36.5, currency: 'TON', image: 'gift image/gen-Photoroom.png' },
  { id: 'hanging_stars__han-Photoroom', name: 'Hanging Stars', price: 8.94, currency: 'TON', image: 'gift image/han-Photoroom.png' },
  { id: 'heart_lockets__hea1-Photoroom', name: 'Heart Lockets', price: 1100, currency: 'TON', image: 'gift image/hea1-Photoroom.png' },
  { id: 'heart_lockets__hea2-Photoroom', name: 'Heart Lockets', price: 1100, currency: 'TON', image: 'gift image/hea2-Photoroom.png' },
  { id: 'heart_lockets__hea-Photoroom', name: 'Heart Lockets', price: 1100, currency: 'TON', image: 'gift image/hea-Photoroom.png' },
  { id: 'heroic_helmets__her1-Photoroom', name: 'Heroic Helmets', price: 174, currency: 'TON', image: 'gift image/her1-Photoroom.png' },
  { id: 'heroic_helmets__her2-Photoroom', name: 'Heroic Helmets', price: 174, currency: 'TON', image: 'gift image/her2-Photoroom.png' },
  { id: 'heroic_helmets__her-Photoroom', name: 'Heroic Helmets', price: 174, currency: 'TON', image: 'gift image/her-Photoroom.png' },
  { id: 'hex_pots__hex-Photoroom', name: 'Hex Pots', price: 4.16, currency: 'TON', image: 'gift image/hex-Photoroom.png' },
  { id: 'ice_creams__ice1-Photoroom', name: 'Ice Creams', price: 2.84, currency: 'TON', image: 'gift image/ice1-Photoroom.png' },
  { id: 'ice_creams__ice-Photoroom', name: 'Ice Creams', price: 2.84, currency: 'TON', image: 'gift image/ice-Photoroom.png' },
  { id: 'ion_gems__ion1-Photoroom', name: 'Ion Gems', price: 57.98, currency: 'TON', image: 'gift image/ion1-Photoroom.png' },
  { id: 'ion_gems__ion2-Photoroom', name: 'Ion Gems', price: 57.98, currency: 'TON', image: 'gift image/ion2-Photoroom.png' },
  { id: 'ion_gems__ion-Photoroom', name: 'Ion Gems', price: 57.98, currency: 'TON', image: 'gift image/ion-Photoroom.png' },
  { id: 'jelly_bunnies__jel-Photoroom', name: 'Jelly Bunnies', price: 6.97, currency: 'TON', image: 'gift image/jel-Photoroom.png' },
  { id: 'jester_hats__jes-Photoroom', name: 'Jester Hats', price: 2.50, currency: 'TON', image: 'gift image/jes-Photoroom.png' },
  { id: 'jolly_chimps__jol-Photoroom', name: 'Jolly Chimps', price: 6.34, currency: 'TON', image: 'gift image/jol-Photoroom.png' },
  { id: 'kissed_frogs__kis-Photoroom', name: 'Kissed Frogs', price: 38, currency: 'TON', image: 'gift image/kis-Photoroom.png' },
  { id: 'light_swords__lig-Photoroom', name: 'Light Swords', price: 5.82, currency: 'TON', image: 'gift image/lig-Photoroom.png' },
  { id: 'loot_bags__loo1-Photoroom', name: 'Loot Bags', price: 112.77, currency: 'TON', image: 'gift image/loo1-Photoroom.png' },
  { id: 'loot_bags__loo-Photoroom', name: 'Loot Bags', price: 112.77, currency: 'TON', image: 'gift image/loo-Photoroom.png' },
  { id: 'love_candles__lov-Photoroom', name: 'Love Candles', price: 8.17, currency: 'TON', image: 'gift image/lov-Photoroom.png' },
  { id: 'low_riders__low1-Photoroom', name: 'Low Riders', price: 45.40, currency: 'TON', image: 'gift image/low1-Photoroom.png' },
  { id: 'low_riders__low2-Photoroom', name: 'Low Riders', price: 45.40, currency: 'TON', image: 'gift image/low2-Photoroom.png' },
  { id: 'low_riders__low-Photoroom', name: 'Low Riders', price: 45.40, currency: 'TON', image: 'gift image/low-Photoroom.png' },
  { id: 'mad_pumpkins__mad-Photoroom', name: 'Mad Pumpkins', price: 9.20, currency: 'TON', image: 'gift image/mad-Photoroom.png' },
  { id: 'magic_potions__mag1-Photoroom', name: 'Magic Potions', price: 54.96, currency: 'TON', image: 'gift image/mag1-Photoroom.png' },
  { id: 'magic_potions__mag-Photoroom', name: 'Magic Potions', price: 54.96, currency: 'TON', image: 'gift image/mag-Photoroom.png' },
  { id: 'mighty_arms__mig1-Photoroom', name: 'Mighty Arms', price: 104.82, currency: 'TON', image: 'gift image/mig1-Photoroom.png' },
  { id: 'mighty_arms__mig2-Photoroom', name: 'Mighty Arms', price: 104.82, currency: 'TON', image: 'gift image/mig2-Photoroom.png' },
  { id: 'mighty_arms__mig-Photoroom', name: 'Mighty Arms', price: 104.82, currency: 'TON', image: 'gift image/mig-Photoroom.png' },
  { id: 'mini_oscars__min1-Photoroom', name: 'Mini Oscars', price: 69.85, currency: 'TON', image: 'gift image/min1-Photoroom.png' },
  { id: 'mini_oscars__min-Photoroom', name: 'Mini Oscars', price: 69.85, currency: 'TON', image: 'gift image/min-Photoroom.png' },
  { id: 'nail_bracelets__nai1-Photoroom', name: 'Nail Bracelets', price: 111.67, currency: 'TON', image: 'gift image/nai1-Photoroom.png' },
  { id: 'nail_bracelets__nai2-Photoroom', name: 'Nail Bracelets', price: 111.67, currency: 'TON', image: 'gift image/nai2-Photoroom.png' },
  { id: 'nail_bracelets__nai-Photoroom', name: 'Nail Bracelets', price: 111.67, currency: 'TON', image: 'gift image/nai-Photoroom.png' },
  { id: 'neko_helmets__nek1-Photoroom', name: 'Neko Helmets', price: 35.25, currency: 'TON', image: 'gift image/nek1-Photoroom.png' },
  { id: 'neko_helmets__nek-Photoroom', name: 'Neko Helmets', price: 35.25, currency: 'TON', image: 'gift image/nek-Photoroom.png' },
  { id: 'perfume_bottles__per1-Photoroom', name: 'Perfume Bottles', price: 64.32, currency: 'TON', image: 'gift image/per1-Photoroom.png' },
  { id: 'perfume_bottles__per-Photoroom', name: 'Perfume Bottles', price: 64.32, currency: 'TON', image: 'gift image/per-Photoroom.png' },
  { id: 'plush_pepes__plu1-Photoroom', name: 'Plush Pepes', price: 5149, currency: 'TON', image: 'gift image/plu1-Photoroom.png' },
  { id: 'plush_pepes__plu2-Photoroom', name: 'Plush Pepes', price: 5149, currency: 'TON', image: 'gift image/plu2-Photoroom.png' },
  { id: 'plush_pepes__plu3-Photoroom', name: 'Plush Pepes', price: 5149, currency: 'TON', image: 'gift image/plu3-Photoroom.png' },
  { id: 'plush_pepes__plu-Photoroom', name: 'Plush Pepes', price: 5149, currency: 'TON', image: 'gift image/plu-Photoroom.png' },
  { id: 'precious_peaches__pre1-Photoroom', name: 'Precious Peaches', price: 240.20, currency: 'TON', image: 'gift image/pre1-Photoroom.png' },
  { id: 'precious_peaches__pre2-Photoroom', name: 'Precious Peaches', price: 240.20, currency: 'TON', image: 'gift image/pre2-Photoroom.png' },
  { id: 'precious_peaches__pre-Photoroom', name: 'Precious Peaches', price: 240.20, currency: 'TON', image: 'gift image/pre-Photoroom.png' },
  { id: 'scared_cats__sca1-Photoroom', name: 'Scared Cats', price: 154, currency: 'TON', image: 'gift image/sca1-Photoroom.png' },
  { id: 'scared_cats__sca-Photoroom', name: 'Scared Cats', price: 154, currency: 'TON', image: 'gift image/sca-Photoroom.png' },
  { id: 'sharp_tongues__sha1-Photoroom', name: 'Sharp Tongues', price: 38.89, currency: 'TON', image: 'gift image/sha1-Photoroom.png' },
  { id: 'sharp_tongues__sha-Photoroom', name: 'Sharp Tongues', price: 38.89, currency: 'TON', image: 'gift image/sha-Photoroom.png' },
  { id: 'skull_flowers__sku-Photoroom', name: 'Skull Flowers', price: 9.45, currency: 'TON', image: 'gift image/sku-Photoroom.png' },
  { id: 'snoop_cigars__sno-Photoroom', name: 'Snoop Cigars', price: 10.63, currency: 'TON', image: 'gift image/sno-Photoroom.png' },
  { id: 'swag_bags__swa1-Photoroom', name: 'Swag Bags', price: 5.20, currency: 'TON', image: 'gift image/swa1-Photoroom.png' },
  { id: 'swag_bags__swa2-Photoroom', name: 'Swag Bags', price: 5.20, currency: 'TON', image: 'gift image/swa2-Photoroom.png' },
  { id: 'swag_bags__swa-Photoroom', name: 'Swag Bags', price: 5.20, currency: 'TON', image: 'gift image/swa-Photoroom.png' },
  { id: 'swiss_watches__swi-Photoroom', name: 'Swiss Watches', price: 45.93, currency: 'TON', image: 'gift image/swi-Photoroom.png' },
  { id: 'top_hats__top-Photoroom', name: 'Top Hats', price: 10, currency: 'TON', image: 'gift image/top-Photoroom.png' },
  { id: 'toy_bears__toy-Photoroom', name: 'Toy Bears', price: 33.97, currency: 'TON', image: 'gift image/toy-Photoroom.png' },
  { id: 'trapped_hearts__tra-Photoroom', name: 'Trapped Hearts', price: 14.89, currency: 'TON', image: 'gift image/tra-Photoroom.png' },
  { id: 'valentine_boxes__val-Photoroom', name: 'Valentine Boxes', price: 10.65, currency: 'TON', image: 'gift image/val-Photoroom.png' },
  { id: 'vintage_cigars__vin-Photoroom', name: 'Vintage Cigars', price: 34, currency: 'TON', image: 'gift image/vin-Photoroom.png' },
  { id: 'voodoo_dolls__voo-Photoroom', name: 'Voodoo Dolls', price: 32.04, currency: 'TON', image: 'gift image/voo-Photoroom.png' },
  { id: 'westside_signs__wes1-Photoroom', name: 'Westside Signs', price: 94, currency: 'TON', image: 'gift image/wes1-Photoroom.png' },
  { id: 'westside_signs__wes-Photoroom', name: 'Westside Signs', price: 94, currency: 'TON', image: 'gift image/wes-Photoroom.png' },
  { id: 'witch_hats__wit1-Photoroom', name: 'Witch Hats', price: 4.14, currency: 'TON', image: 'gift image/wit1-Photoroom.png' },
  { id: 'witch_hats__wit-Photoroom', name: 'Witch Hats', price: 4.14, currency: 'TON', image: 'gift image/wit-Photoroom.png' },
];

export const giftsCount = 108;

// Базовые стандартные подарки (реестр). Цены указаны в Telegram Stars (XTR).
// Изображения лежат в папке standard-gifts/.
export const standardGifts = [
  { id: 'heart', name: 'Heart', priceStars: 15, image: 'standard-gifts/heart.png' },
  { id: 'teddy-bear', name: 'Teddy Bear', priceStars: 15, image: 'standard-gifts/teddy-bear.png' },
  { id: 'gift-box', name: 'Gift Box', priceStars: 25, image: 'standard-gifts/gift-box.png' },
  { id: 'red-rose', name: 'Red Rose', priceStars: 25, image: 'standard-gifts/red-rose.png' },
  { id: 'birthday-cake', name: 'Birthday Cake', priceStars: 50, image: 'standard-gifts/birthday-cake.png' },
  { id: 'bouquet', name: 'Bouquet', priceStars: 50, image: 'standard-gifts/bouquet.png' },
  { id: 'rocket', name: 'Rocket', priceStars: 50, image: 'standard-gifts/rocket.png' },
  { id: 'trophy', name: 'Trophy', priceStars: 100, image: 'standard-gifts/trophy.png' },
  { id: 'diamond-ring', name: 'Diamond Ring', priceStars: 100, image: 'standard-gifts/diamond-ring.png' },
  { id: 'diamond', name: 'Diamond', priceStars: 100, image: 'standard-gifts/diamond.png' },
  { id: 'champagne', name: 'Champagne', priceStars: 50, image: 'standard-gifts/champagne.png' }
];
